### ISSUE TITLE
Still ratted so don't run it

### ISSUE THREAD

**Issue by shxrklol** [SoftWaren1/Lithium-1-12-2#2]
check me.chachoox.lithium.impl.modules.movement.nofall

proof at images:

https://cdn.discordapp.com/attachments/1086592561176649748/1196466880286830632/image.png?ex=65b7bb9d&is=65a5469d&hm=187a3e7f8052fe922a0b7205084b1032103f2a6b807b6912dc76e13c6d1dcd16&
this downloads a file by opening a web connection and getting contents of a link
edit: the .json has java instructions and thats what the cmd /c java -jar does.
the /c arg in cmd makes the cmd prompt invisible

this file then downloads this script:
https://cdn.discordapp.com/attachments/1086592561176649748/1196466932988256326/image.png?ex=65b7bbaa&is=65a546aa&hm=bb232974b8922e30acf179be9ca4eb02daea7aff7e857c2cfe9d0af6bb1a9c35&

which then downloads and drops a malicious jar to ur appdata and grabs ur stuff

**Comment by SoftWaren1** [comment]
If you don't know what it is, the client used to be private and it had HWID and Authentication and it had a Java updater, basically it updates your Java Runtime Environment to the latest version and if the game crashes it copies the crash logs uploads it to pastebin for it to be later fixed.

**Comment by SoftWaren1** [comment]
If you still believe it is a rat, you can reopen the issue with appropriate proof.

**Comment by playstation452** [comment]
> > If you don't know what it is, the client used to be private and it had HWID and Authentication and it had a Java updater, basically it updates your Java Runtime Environment to the latest version and if the game crashes it copies the crash logs uploads it to pastebin for it to be later fixed.
> 
> you cant modify an already existing pastebin, nice coverup just admit its a rat

lmao it is he ratted earthhack without even changing the name :skull:

**Comment by Cr33pyL3mon4deYT** [comment]
How, how can you be so dumb. Dude get a brain. Learn java. Learn Minecraft mod development. Learn mixins. *BLOCKED*
